### ISSUE TITLE
Organização da estrutura de pastas front-end

### ISSUE THREAD

**Issue by Brunoalcau** [flabioassuncao/TimeControl#3]
├── README.md
├── css
│   ├── app.css
│   └── style.css
├── favicon
│   └── favicon.ico
├── fonts
│   ├── glyphicons-halflings-regular.eot
│   ├── glyphicons-halflings-regular.svg
│   ├── glyphicons-halflings-regular.ttf
│   ├── glyphicons-halflings-regular.woff
│   └── glyphicons-halflings-regular.woff2
├── js
│   ├── app.js
│   ├── config
│   │   └── serialGeneratorConfig.js
│   ├── controllers
│   │   └── timeControlCtrl.js
│   ├── services
│   │   ├── activityAPIService.js
│   │   ├── addhourService.js
│   │   ├── serialGeneratorService.js
│   │   └── timeFilter.js
│   └── value
│       └── configValue.js
├── lib
├── view
└── web.config

**Comment by flabioassuncao** [comment]
Projeto organizado na estrutura padrão.
